FROM node:20-alpine

WORKDIR /app

RUN npm install -g tsx typescript

RUN adduser -D runner
RUN chown -R runner:runner /app

COPY run.sh /run.sh
RUN chmod +x /run.sh

USER runner

ENTRYPOINT ["/run.sh"]